
USE [master]
GO
/****** Object:  Database [Controle_Acesso]    Script Date: 30/09/2026 16:16:03 ******/
CREATE DATABASE [Controle_Acesso]
 CONTAINMENT = NONE
GO
ALTER DATABASE [Controle_Acesso] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Controle_Acesso].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Controle_Acesso] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Controle_Acesso] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Controle_Acesso] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Controle_Acesso] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Controle_Acesso] SET ARITHABORT OFF 
GO
ALTER DATABASE [Controle_Acesso] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Controle_Acesso] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Controle_Acesso] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Controle_Acesso] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Controle_Acesso] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Controle_Acesso] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Controle_Acesso] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Controle_Acesso] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Controle_Acesso] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Controle_Acesso] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Controle_Acesso] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Controle_Acesso] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Controle_Acesso] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Controle_Acesso] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Controle_Acesso] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Controle_Acesso] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Controle_Acesso] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Controle_Acesso] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Controle_Acesso] SET  MULTI_USER 
GO
ALTER DATABASE [Controle_Acesso] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Controle_Acesso] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Controle_Acesso] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Controle_Acesso] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Controle_Acesso] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Controle_Acesso] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Controle_Acesso] SET QUERY_STORE = ON
GO
ALTER DATABASE [Controle_Acesso] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Controle_Acesso]
GO
/****** Object:  Table [dbo].[tblACESSO]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblACESSO](
	[ACE_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DATA_] [date] NULL,
	[ENTRADA] [time](7) NULL,
	[SAIDA] [time](7) NULL,
	[DESTINO] [varchar](50) NULL,
	[USE_CODIGO] [int] NULL,
	[FUN_CODIGO] [int] NULL,
	[VIS_CODIGO] [int] NULL,
	[EMP_CODIGO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACE_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblASSOCIADO]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblASSOCIADO](
	[ASS_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](20) NULL,
	[NUMERO] [varchar](11) NULL,
	[SEXO] [varchar](15) NULL,
	[DEPARTAMENTO] [varchar](30) NULL,
	[EMP_CODIGO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ASS_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblEMPRESA]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblEMPRESA](
	[EMP_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](20) NULL,
	[ANDAR] [int] NULL,
	[NSALA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EMP_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblENTREGA]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblENTREGA](
	[ENT_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TIPO] [varchar](20) NULL,
	[RECEBIDO] [varchar](30) NULL,
	[ACE_CODIGO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ENT_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblFUNCIONARIO]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblFUNCIONARIO](
	[FUN_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NULL,
	[DATA_NASCIMENTO] [date] NULL,
	[NUMERO] [varchar](11) NULL,
	[EMAIL] [varchar](50) NULL,
	[CPF] [varchar](20) NULL,
	[SEXO] [varchar](15) NULL,
	[DEPARTAMENTO] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[FUN_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTELEFONE]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTELEFONE](
	[TEL_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TELEFONE] [varchar](11) NULL,
	[EMP_CODIGO] [int] NULL,
	[TTE_CODIGO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TEL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblTIPO_TELEFONE]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblTIPO_TELEFONE](
	[TTE_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[TTE_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblUSUARIO]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUSUARIO](
	[USE_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NULL,
	[NUMERO] [varchar](12) NULL,
	[EMAIL] [varchar](50) NULL,
	[SEXO] [varchar](15) NULL,
	[LOGIN] [varchar](20) NULL,
	[SENHA] [varchar](100) NULL,
	[ATIVO] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[USE_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblVISITANTE]    Script Date: 30/09/2026 16:16:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblVISITANTE](
	[VIS_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](20) NULL,
	[RG] [varchar](15) NULL,
	[SEXO] [varchar](15) NULL,
	[DEPARTAMENTO] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[VIS_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tblACESSO] ON 

INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (1, CAST(N'2018-02-19' AS Date), CAST(N'09:00:00' AS Time), CAST(N'11:00:00' AS Time), N'ADMINISTRAÇÃO', NULL, 1, 1, 2)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (2, CAST(N'2018-03-25' AS Date), CAST(N'10:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RHSOLUCÕES', NULL, 2, 2, 3)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (3, CAST(N'2018-05-12' AS Date), CAST(N'12:00:00' AS Time), CAST(N'15:50:00' AS Time), N'ESTOQUE', NULL, 3, 3, 4)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (4, CAST(N'2018-02-20' AS Date), CAST(N'18:00:00' AS Time), CAST(N'22:50:00' AS Time), N'QUALIDADEECONTROLE', NULL, 2, 4, 5)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (5, CAST(N'2018-05-11' AS Date), CAST(N'10:00:00' AS Time), CAST(N'23:50:00' AS Time), N'GESTÃODEPROJETO', NULL, 1, 1, 7)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (6, CAST(N'2018-05-05' AS Date), CAST(N'15:00:00' AS Time), CAST(N'20:50:00' AS Time), N'AUDITORIAINTERNA', NULL, 3, 4, 8)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (7, CAST(N'2018-06-06' AS Date), CAST(N'02:00:00' AS Time), CAST(N'04:00:00' AS Time), N'CONTABILIDADE', NULL, 2, 1, 9)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (8, CAST(N'2018-07-07' AS Date), CAST(N'10:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RECEPÇÃO', NULL, 1, 3, 10)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (9, CAST(N'2018-08-08' AS Date), CAST(N'11:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RHINFO', NULL, 2, 2, 5)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (10, CAST(N'2018-02-02' AS Date), CAST(N'10:00:00' AS Time), CAST(N'10:50:00' AS Time), N'TELEMARKETING', NULL, 2, 4, 7)
SET IDENTITY_INSERT [dbo].[tblACESSO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblASSOCIADO] ON 

INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (1, N'RAFAEL CORREIA', N'11927916343', N'MASCULINO', N'ADMINISTRAÇÃO', 1)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (2, N'JOÃO ALMEIDA', N'11935472079', N'MASCULINO', N'RHSOLUCÕES', 4)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (3, N'BIANCA SANTOS', N'11921515304', N'FEMININO', N'ESTOQUE', 3)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (4, N'VITORIA SOUZA', N'11938844643', N'FEMININO', N'QUALIDADEECONTROLE', 2)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (5, N'KAUA MELO', N'11923328143', N'MASCULINO', N'GESTÃODEPROJETO', 6)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (6, N'MARCOS PEREIRA', N'11987456258', N'MASCULINO', N'AUDITORIAINTERNA', 9)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (7, N'VITOR FERREIRA', N'11927351258', N'MASCULINO', N'CONTABILIDADE', 7)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (8, N'BRUNO RODRIGUES', N'11931493378', N'MASCULINO', N'RECEPÇÃO', 5)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (9, N'REBECA BARROS ', N'11924256737', N'FEMININO', N'RHINFO', 8)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (10, N'MARIA CUNHA', N'11927178365', N'FEMININO', N'TELEMARKETING', 10)
SET IDENTITY_INSERT [dbo].[tblASSOCIADO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblEMPRESA] ON 

INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (1, N'ADMINISTRAÇÃO', 1, 1)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (2, N'RHSOLUCÕES', 2, 3)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (3, N'ESTOQUE', 3, 5)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (4, N'QUALIDADEECONTROLE', 4, 7)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (5, N'GESTÃODEPROJETO', 5, 9)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (6, N'AUDITORIAINTERNA', 1, 2)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (7, N'CONTABILIDADE', 2, 4)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (8, N'RECEPÇÃO', 3, 6)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (9, N'RHINFO', 4, 8)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (10, N'TELEMARKETING', 5, 10)
SET IDENTITY_INSERT [dbo].[tblEMPRESA] OFF
GO
SET IDENTITY_INSERT [dbo].[tblENTREGA] ON 

INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (1, N'PACOTE', N'GUILHERME ALVES', 2)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (2, N'CARTA', N'JOÃO CARDOSO', 1)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (3, N'PACOTE', N'LUÍS PEREIRA', 4)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (4, N'CARTA', N'ANTÔNIO BARROS', 5)
SET IDENTITY_INSERT [dbo].[tblENTREGA] OFF
GO
SET IDENTITY_INSERT [dbo].[tblFUNCIONARIO] ON 

INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (1, N'DIEGO ARNALDO', CAST(N'1984-12-10' AS Date), N'13926621441', N'DIEGOARNALDO@GMAIL.COM', N'78167586855', N'MASCULINO', N'ADMINISTRAÇÃO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (2, N'ANA CLARA ', CAST(N'1991-05-12' AS Date), N'13927328754', N'ANACLARA@GMAIL.COM', N'35644244822', N'FEMININO', N'RHSOLUCÕES')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (3, N'JOSÉ MAXIMIANO', CAST(N'1983-05-07' AS Date), N'16927962335', N'JOSEMAXIMIANO@GMAIL.COM', N'54375214805', N'MASCULINO', N'ESTOQUE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (4, N'IVAN JAIR', CAST(N'1998-07-11' AS Date), N'17923360137', N'IVANJAIR@GMAIL.COM', N'11628793864', N'MASCULINO', N'QUALIDADEECONTROLE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (5, N'BIANCA RITA', CAST(N'1985-11-09' AS Date), N'16922062690', N'BIANCARITA@GMAIL.COM', N'17596278876', N'FEMININO', N'GESTÃODEPROJETO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (6, N'ARMANDO CHARLES', CAST(N'1979-04-02' AS Date), N'14924581323', N'ARMANDOCHARLES@GMAIL.COM', N'17726844817', N'MASCULINO', N'AUDITORIAINTERNA')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (7, N'BEATRIZ MARÉS', CAST(N'1987-10-03' AS Date), N'16930871759', N'BEATRIZMARES@GMAIL.COM', N'82215161809', N'FEMININO', N'CONTABILIDADE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (8, N'CAROLINA LARISSA', CAST(N'1996-01-03' AS Date), N'19937421448', N'CAROLINALARISSA@GMAIL.COM', N'95613091811', N'FEMININO', N'RECEPÇÃO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (9, N'CRISTINA LEONARA', CAST(N'2001-08-06' AS Date), N'17925245392', N'CRISTINALEONARA@GMAIL.COM', N'86777331832', N'FEMININO', N'RHINFO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (10, N'MÁRCIO BARROS', CAST(N'1978-12-01' AS Date), N'11921216588', N'MARCIOBARROS@GMAIL.COM', N'83548453899', N'MASCULINO', N'TELEMARKETING')
SET IDENTITY_INSERT [dbo].[tblFUNCIONARIO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblTELEFONE] ON 

INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (1, N'11955474525', 1, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (2, N'4283-1723', 2, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (3, N'4181-1429', 3, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (4, N'11934365847', 4, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (5, N'4281-5236', 5, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (6, N'11926245110', 6, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (7, N'4223-2525', 7, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (8, N'11986258962', 8, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (9, N'4181-1400', 9, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (10, N'4181-1426', 9, 1)
SET IDENTITY_INSERT [dbo].[tblTELEFONE] OFF
GO
SET IDENTITY_INSERT [dbo].[tblTIPO_TELEFONE] ON 

INSERT [dbo].[tblTIPO_TELEFONE] ([TTE_CODIGO], [DESCRICAO]) VALUES (1, N'FIXO')
INSERT [dbo].[tblTIPO_TELEFONE] ([TTE_CODIGO], [DESCRICAO]) VALUES (2, N'CELULAR')
SET IDENTITY_INSERT [dbo].[tblTIPO_TELEFONE] OFF
GO
SET IDENTITY_INSERT [dbo].[tblUSUARIO] ON 

INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (1, N'GUILHERME DE JESUS', N'11955474525', N'GUILHERMEDEJESUS@HOTMAIL.COM', N'MASCULINO', N'GUILHERME.JESUS', N'4c29f94d61f96dde64a65202a6de6700', 1)
INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (2, N'AMANDA MAIA', N'11934365847', N'AMANDAMAIA@HOTMAIL.COM', N'FEMININO', N'AMANDA.MAIA', N'4c29f94d61f96dde64a65202a6de6700', 1)
INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (3, N'THAÍS ALMEIDA', N'11926245110', N'THAISALMEIDA@HOTMAIL.COM', N'FEMININO', N'THAIS.ALMEIDA', N'4c29f94d61f96dde64a65202a6de6700', 1)
SET IDENTITY_INSERT [dbo].[tblUSUARIO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblVISITANTE] ON 

INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (1, N'LUCAS FERREIRA', N'326541759', N'MASCULINO', N'ADMINISTRAÇÃO')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (2, N'DANIEL ALVES', N'968556364', N'MASCULINO', N'RHSOLUCÕES')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (3, N'DIEGO SILVA', N'968162782', N'MASCULINO', N'ESTOQUE')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (4, N'ANA FERNADES', N'786532154', N'FEMININO', N'QUALIDADEECONTROLE')
SET IDENTITY_INSERT [dbo].[tblVISITANTE] OFF
GO
ALTER TABLE [dbo].[tblACESSO]  WITH CHECK ADD FOREIGN KEY([EMP_CODIGO])
REFERENCES [dbo].[tblEMPRESA] ([EMP_CODIGO])
GO
ALTER TABLE [dbo].[tblACESSO]  WITH CHECK ADD FOREIGN KEY([FUN_CODIGO])
REFERENCES [dbo].[tblFUNCIONARIO] ([FUN_CODIGO])
GO
ALTER TABLE [dbo].[tblACESSO]  WITH CHECK ADD FOREIGN KEY([USE_CODIGO])
REFERENCES [dbo].[tblUSUARIO] ([USE_CODIGO])
GO
ALTER TABLE [dbo].[tblACESSO]  WITH CHECK ADD FOREIGN KEY([VIS_CODIGO])
REFERENCES [dbo].[tblVISITANTE] ([VIS_CODIGO])
GO
ALTER TABLE [dbo].[tblASSOCIADO]  WITH CHECK ADD FOREhIGN KEY([EMP_CODIGO])
REFERENCES [dbo].[tblEMPRESA] ([EMP_CODIGO])
GO
ALTER TABLE [dbo].[tblENTREGA]  WITH CHECK ADD FOREIGN KEY([ACE_CODIGO])
REFERENCES [dbo].[tblACESSO] ([ACE_CODIGO])
GO
ALTER TABLE [dbo].[tblTELEFONE]  WITH CHECK ADD FOREIGN KEY([EMP_CODIGO])
REFERENCES [dbo].[tblEMPRESA] ([EMP_CODIGO])
GO
ALTER TABLE [dbo].[tblTELEFONE]  WITH CHECK ADD FOREIGN KEY([TTE_CODIGO])
REFERENCES [dbo].[tblTIPO_TELEFONE] ([TTE_CODIGO])
GO
USE [master]
GO
ALTER DATABASE [Controle_Acesso] SET  READ_WRITE 
GO

h

USE [Controle_Acesso]
GO
SET IDENTITY_INSERT [dbo].[tblVISITANTE] ON 

INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (1, N'LUCAS FERREIRA', N'326541759', N'MASCULINO', N'ADMINISTRAÇÃO')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (2, N'DANIEL ALVES', N'968556364', N'MASCULINO', N'RHSOLUCÕES')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (3, N'DIEGO SILVA', N'968162782', N'MASCULINO', N'ESTOQUE')
INSERT [dbo].[tblVISITANTE] ([VIS_CODIGO], [NOME], [RG], [SEXO], [DEPARTAMENTO]) VALUES (4, N'ANA FERNADES', N'786532154', N'FEMININO', N'QUALIDADEECONTROLE')
SET IDENTITY_INSERT [dbo].[tblVISITANTE] OFF
GO
SET IDENTITY_INSERT [dbo].[tblEMPRESA] ON 

INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (1, N'ADMINISTRAÇÃO', 1, 1)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (2, N'RHSOLUCÕES', 2, 3)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (3, N'ESTOQUE', 3, 5)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (4, N'QUALIDADEECONTROLE', 4, 7)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (5, N'GESTÃODEPROJETO', 5, 9)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (6, N'AUDITORIAINTERNA', 1, 2)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (7, N'CONTABILIDADE', 2, 4)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (8, N'RECEPÇÃO', 3, 6)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (9, N'RHINFO', 4, 8)
INSERT [dbo].[tblEMPRESA] ([EMP_CODIGO], [NOME], [ANDAR], [NSALA]) VALUES (10, N'TELEMARKETING', 5, 10)
SET IDENTITY_INSERT [dbo].[tblEMPRESA] OFF
GO
SET IDENTITY_INSERT [dbo].[tblUSUARIO] ON 

INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (1, N'GUILHERME DE JESUS', N'11955474525', N'GUILHERMEDEJESUS@HOTMAIL.COM', N'MASCULINO', N'GUILHERME.JESUS', N'4c29f94d61f96dde64a65202a6de6700', 1)
INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (2, N'AMANDA MAIA', N'11934365847', N'AMANDAMAIA@HOTMAIL.COM', N'FEMININO', N'AMANDA.MAIA', N'4c29f94d61f96dde64a65202a6de6700', 1)
INSERT [dbo].[tblUSUARIO] ([USE_CODIGO], [NOME], [NUMERO], [EMAIL], [SEXO], [LOGIN], [SENHA], [ATIVO]) VALUES (3, N'THAÍS ALMEIDA', N'11926245110', N'THAISALMEIDA@HOTMAIL.COM', N'FEMININO', N'THAIS.ALMEIDA', N'4c29f94d61f96dde64a65202a6de6700', 1)
SET IDENTITY_INSERT [dbo].[tblUSUARIO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblFUNCIONARIO] ON 

INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (1, N'DIEGO ARNALDO', CAST(N'1984-12-10' AS Date), N'13926621441', N'DIEGOARNALDO@GMAIL.COM', N'78167586855', N'MASCULINO', N'ADMINISTRAÇÃO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (2, N'ANA CLARA ', CAST(N'1991-05-12' AS Date), N'13927328754', N'ANACLARA@GMAIL.COM', N'35644244822', N'FEMININO', N'RHSOLUCÕES')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (3, N'JOSÉ MAXIMIANO', CAST(N'1983-05-07' AS Date), N'16927962335', N'JOSEMAXIMIANO@GMAIL.COM', N'54375214805', N'MASCULINO', N'ESTOQUE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (4, N'IVAN JAIR', CAST(N'1998-07-11' AS Date), N'17923360137', N'IVANJAIR@GMAIL.COM', N'11628793864', N'MASCULINO', N'QUALIDADEECONTROLE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (5, N'BIANCA RITA', CAST(N'1985-11-09' AS Date), N'16922062690', N'BIANCARITA@GMAIL.COM', N'17596278876', N'FEMININO', N'GESTÃODEPROJETO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (6, N'ARMANDO CHARLES', CAST(N'1979-04-02' AS Date), N'14924581323', N'ARMANDOCHARLES@GMAIL.COM', N'17726844817', N'MASCULINO', N'AUDITORIAINTERNA')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (7, N'BEATRIZ MARÉS', CAST(N'1987-10-03' AS Date), N'16930871759', N'BEATRIZMARES@GMAIL.COM', N'82215161809', N'FEMININO', N'CONTABILIDADE')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (8, N'CAROLINA LARISSA', CAST(N'1996-01-03' AS Date), N'19937421448', N'CAROLINALARISSA@GMAIL.COM', N'95613091811', N'FEMININO', N'RECEPÇÃO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (9, N'CRISTINA LEONARA', CAST(N'2001-08-06' AS Date), N'17925245392', N'CRISTINALEONARA@GMAIL.COM', N'86777331832', N'FEMININO', N'RHINFO')
INSERT [dbo].[tblFUNCIONARIO] ([FUN_CODIGO], [NOME], [DATA_NASCIMENTO], [NUMERO], [EMAIL], [CPF], [SEXO], [DEPARTAMENTO]) VALUES (10, N'MÁRCIO BARROS', CAST(N'1978-12-01' AS Date), N'11921216588', N'MARCIOBARROS@GMAIL.COM', N'83548453899', N'MASCULINO', N'TELEMARKETING')
SET IDENTITY_INSERT [dbo].[tblFUNCIONARIO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblACESSO] ON 

INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (1, CAST(N'2018-02-19' AS Date), CAST(N'09:00:00' AS Time), CAST(N'11:00:00' AS Time), N'ADMINISTRAÇÃO', NULL, 1, 1, 2)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (2, CAST(N'2018-03-25' AS Date), CAST(N'10:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RHSOLUCÕES', NULL, 2, 2, 3)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (3, CAST(N'2018-05-12' AS Date), CAST(N'12:00:00' AS Time), CAST(N'15:50:00' AS Time), N'ESTOQUE', NULL, 3, 3, 4)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (4, CAST(N'2018-02-20' AS Date), CAST(N'18:00:00' AS Time), CAST(N'22:50:00' AS Time), N'QUALIDADEECONTROLE', NULL, 2, 4, 5)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (5, CAST(N'2018-05-11' AS Date), CAST(N'10:00:00' AS Time), CAST(N'23:50:00' AS Time), N'GESTÃODEPROJETO', NULL, 1, 1, 7)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (6, CAST(N'2018-05-05' AS Date), CAST(N'15:00:00' AS Time), CAST(N'20:50:00' AS Time), N'AUDITORIAINTERNA', NULL, 3, 4, 8)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (7, CAST(N'2018-06-06' AS Date), CAST(N'02:00:00' AS Time), CAST(N'04:00:00' AS Time), N'CONTABILIDADE', NULL, 2, 1, 9)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (8, CAST(N'2018-07-07' AS Date), CAST(N'10:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RECEPÇÃO', NULL, 1, 3, 10)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (9, CAST(N'2018-08-08' AS Date), CAST(N'11:00:00' AS Time), CAST(N'11:50:00' AS Time), N'RHINFO', NULL, 2, 2, 5)
INSERT [dbo].[tblACESSO] ([ACE_CODIGO], [DATA_], [ENTRADA], [SAIDA], [DESTINO], [USE_CODIGO], [FUN_CODIGO], [VIS_CODIGO], [EMP_CODIGO]) VALUES (10, CAST(N'2018-02-02' AS Date), CAST(N'10:00:00' AS Time), CAST(N'10:50:00' AS Time), N'TELEMARKETING', NULL, 2, 4, 7)
SET IDENTITY_INSERT [dbo].[tblACESSO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblTIPO_TELEFONE] ON 

INSERT [dbo].[tblTIPO_TELEFONE] ([TTE_CODIGO], [DESCRICAO]) VALUES (1, N'FIXO')
INSERT [dbo].[tblTIPO_TELEFONE] ([TTE_CODIGO], [DESCRICAO]) VALUES (2, N'CELULAR')
SET IDENTITY_INSERT [dbo].[tblTIPO_TELEFONE] OFF
GO
SET IDENTITY_INSERT [dbo].[tblTELEFONE] ON 

INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (1, N'11955474525', 1, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (2, N'4283-1723', 2, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (3, N'4181-1429', 3, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (4, N'11934365847', 4, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (5, N'4281-5236', 5, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (6, N'11926245110', 6, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (7, N'4223-2525', 7, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (8, N'11986258962', 8, 2)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (9, N'4181-1400', 9, 1)
INSERT [dbo].[tblTELEFONE] ([TEL_CODIGO], [TELEFONE], [EMP_CODIGO], [TTE_CODIGO]) VALUES (10, N'4181-1426', 9, 1)
SET IDENTITY_INSERT [dbo].[tblTELEFONE] OFF
GO
SET IDENTITY_INSERT [dbo].[tblASSOCIADO] ON 

INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (1, N'RAFAEL CORREIA', N'11927916343', N'MASCULINO', N'ADMINISTRAÇÃO', 1)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (2, N'JOÃO ALMEIDA', N'11935472079', N'MASCULINO', N'RHSOLUCÕES', 4)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (3, N'BIANCA SANTOS', N'11921515304', N'FEMININO', N'ESTOQUE', 3)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (4, N'VITORIA SOUZA', N'11938844643', N'FEMININO', N'QUALIDADEECONTROLE', 2)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (5, N'KAUA MELO', N'11923328143', N'MASCULINO', N'GESTÃODEPROJETO', 6)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (6, N'MARCOS PEREIRA', N'11987456258', N'MASCULINO', N'AUDITORIAINTERNA', 9)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (7, N'VITOR FERREIRA', N'11927351258', N'MASCULINO', N'CONTABILIDADE', 7)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (8, N'BRUNO RODRIGUES', N'11931493378', N'MASCULINO', N'RECEPÇÃO', 5)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (9, N'REBECA BARROS ', N'11924256737', N'FEMININO', N'RHINFO', 8)
INSERT [dbo].[tblASSOCIADO] ([ASS_CODIGO], [NOME], [NUMERO], [SEXO], [DEPARTAMENTO], [EMP_CODIGO]) VALUES (10, N'MARIA CUNHA', N'11927178365', N'FEMININO', N'TELEMARKETING', 10)
SET IDENTITY_INSERT [dbo].[tblASSOCIADO] OFF
GO
SET IDENTITY_INSERT [dbo].[tblENTREGA] ON 

INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (1, N'PACOTE', N'GUILHERME ALVES', 2)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (2, N'CARTA', N'JOÃO CARDOSO', 1)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (3, N'PACOTE', N'LUÍS PEREIRA', 4)
INSERT [dbo].[tblENTREGA] ([ENT_CODIGO], [TIPO], [RECEBIDO], [ACE_CODIGO]) VALUES (4, N'CARTA', N'ANTÔNIO BARROS', 5)
SET IDENTITY_INSERT [dbo].[tblENTREGA] OFF
GO
